In [1]:
import numpy as np

# Tworzenie wektora

In [2]:
# stworzenie wektora o długości 4
v = np.array([1, 2, 3, 4], dtype=np.float32)
print(v)
print(type(v))
print(v.shape)

[1. 2. 3. 4.]
<class 'numpy.ndarray'>
(4,)


In [3]:
# możemy też przekonwertować zwykłą listę
lista = [1, 2, 3]
print(type(lista))
k = np.array(lista)
print(type(k))

<class 'list'>
<class 'numpy.ndarray'>


# Dodawanie i odejmowanie wektorów

In [4]:
v = np.array([1, 2, 3, 4], dtype=np.float32)
w = np.array([0.1, 0.2, 0.3, 0.4], dtype=np.float32)
print(f'v + w: {v + w}')
print(f'v - w: {v - w}')

v + w: [1.1 2.2 3.3 4.4]
v - w: [0.9 1.8 2.7 3.6]


# Mnożenie wektora przez skalar

In [5]:
v = np.array([1, 2, 3, 4], dtype=np.float32)
a = 5
print(f'a * v: {a * v}')

a * v: [ 5. 10. 15. 20.]


# Iloczyn skalarny

In [6]:
v = np.array([1, 2, 3])
w = np.array([1, 10, 100])

a = np.dot(v, w)
b = v @ w

print(f'v o w: {a}')
print(f'v @ w: {b}')

v o w: 321
v @ w: 321


# Tworzenie macierzy

In [7]:
A = np.array([[1, 2, 3],
              [4, 5, 6]], dtype=np.int32)
print(A)
print(type(A))
print(A.shape)
print(f'Wyraz 1, 0: {A[1, 0]}')

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
(2, 3)
Wyraz 1, 0: 4


In [8]:
# możemy też stworzyć sztuczny wektor wierszowy...
v = np.array([[1, 2, 3]])
print(v)
print(v.shape)

[[1 2 3]]
(1, 3)


In [9]:
# ...oraz sztuczny kolumnowy
a = np.array([[1], [2], [3]])
print(a)
print(a.shape)
# UWAGA, NUMPY NIE TRAKTUJE TEGO JAK WEKTORY, ALE JAK MACIERZE!

[[1]
 [2]
 [3]]
(3, 1)


# Operacje na wycinkach

In [10]:
A = np.array([[1, 2, 3],
              [4, 5, 6]], dtype=np.int32)
# wypiszmy macierz
print(A)
print('\n=================================\n')
# weźmy całą pierwszą kolumnę
a = A[:, 0]
print(f'Bierzemy całą pierwszą kolumnę używając A[:, 0]: {a}')
print(f'Typ kolumny: {type(a)} oraz jej wymiary: {a.shape}')
print('\n=================================\n')
# weźmy teraz cały pierwszy wiersz
b = A[0, :]
print(f'Bierzemy cały pierwszy wiersz używając A[0, :]: {b}')
print(f'Typ wiersza: {type(b)} oraz jego wymiary: {b.shape}')
print('\n=================================\n')

# weźmy wszystkie wyrazy do drugiej kolumny
B = A[:, :2]
print(f'Pierwsze dwie kolumny używając A[:, :2]:\n {B}')
print(f'Typ nowej macierzy: {type(B)} oraz jej wymiary: {B.shape}')

[[1 2 3]
 [4 5 6]]


Bierzemy całą pierwszą kolumnę używając A[:, 0]: [1 4]
Typ kolumny: <class 'numpy.ndarray'> oraz jej wymiary: (2,)


Bierzemy cały pierwszy wiersz używając A[0, :]: [1 2 3]
Typ wiersza: <class 'numpy.ndarray'> oraz jego wymiary: (3,)


Pierwsze dwie kolumny używając A[:, :2]:
 [[1 2]
 [4 5]]
Typ nowej macierzy: <class 'numpy.ndarray'> oraz jej wymiary: (2, 2)


# Dodawanie macierzy

In [11]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[0.1, 0.2], [0.3, 0.4]])
print(A + B)

[[1.1 2.2]
 [3.3 4.4]]


# Mnożenie przez skalar

In [12]:
A = np.array([[1, 2], [3, 4]])
b = 10
print(b * A)

[[10 20]
 [30 40]]


# Mnożenie macierzy

In [13]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
B = np.array([[0.1, 0.4, 0.5], [0.7, 0.8, 0.9], [10, 11, 20]])
print(np.dot(A, B))

[[ 31.5  35.   62.3]
 [ 63.9  71.6 126.5]
 [ 96.3 108.2 190.7]
 [128.7 144.8 254.9]]


# Mnożenie macierzy przez wektor

In [14]:
A = np.array([[1, 2, 4], [5, 6, 7]])
v = np.array([1, 10, 100])
print(f'Wymiary A: {A.shape}')
print(f'Wymiary v: {v.shape}\n')

# damy radę?
# A o v, damy radę?
print(f'A o v: {np.dot(A, v)}')
# Oczywiście! A w drugą stronę, v o A?
print(f'v o A: {np.dot(v, A)}')
# NOPE

Wymiary A: (2, 3)
Wymiary v: (3,)

A o v: [421 765]


ValueError: shapes (3,) and (2,3) not aligned: 3 (dim 0) != 2 (dim 0)

In [15]:
# natomiast w takiej sytuacji:
A = np.array([[1, 2], [3, 4]])
v = np.array([1, 10])
print(f'Wymiary A: {A.shape}')
print(f'Wymiary v: {v.shape}\n')

# damy radę?
print(f'A o v: {np.dot(A, v)}')
print(f'v o A: {np.dot(v, A)}')

Wymiary A: (2, 2)
Wymiary v: (2,)

A o v: [21 43]
v o A: [31 42]


# Transpozycja

In [16]:
A = np.array([[1, 2], [3, 4], [5, 6]])
print('Macierz A: ')
print(A)
print(f'Wymiary: {A.shape}')
print('\n=================================\n')
# po transpozycji
print('Transponowana macierz A: ')
print(A.T)
print(f'Wymiary: {A.T.shape}')

Macierz A: 
[[1 2]
 [3 4]
 [5 6]]
Wymiary: (3, 2)


Transponowana macierz A: 
[[1 3 5]
 [2 4 6]]
Wymiary: (2, 3)


In [17]:
# pytanie, czy możemy przetransponować wektor?
v = np.array([1, 2, 3])
print(f'Wektor v: {v}')
print(f'Wymiary: {v.shape}')
print('\n=================================\n')
print(f'Wektor v transponowany: {v.T}')
print(f'Wymiary: {v.T.shape}')
# można, ale nic to nie zrobi!

Wektor v: [1 2 3]
Wymiary: (3,)


Wektor v transponowany: [1 2 3]
Wymiary: (3,)


# Reshapowanie macierzy

In [18]:
A = np.array([[1, 2, 3], [4, 5, 6]])
print('Macierz A:')
print(A)
print(f'Wymiary: {A.shape}')
print('\n=================================\n')
B = A.reshape(6, 1)
print('Macierz B:')
print(B)
print(f'Wymiary: {B.shape}')

Macierz A:
[[1 2 3]
 [4 5 6]]
Wymiary: (2, 3)


Macierz B:
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
Wymiary: (6, 1)


In [19]:
# jeżeli chcemy mieć konkretną ilość np. wierszy, ale nie chcemy liczyć ile to będzie kolumn, numpy zrobi to za nas
A = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
print('Macierz A:')
print(A)
print(f'Wymiary: {A.shape}')
print('\n=================================\n')
B = A.reshape(4, -1)
print('Macierz B:')
print(B)
print(f'Wymiary: {B.shape}')

Macierz A:
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
Wymiary: (6, 2)


Macierz B:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Wymiary: (4, 3)


# Przydatne funkcje dotyczące tworzenia wektorów i macierzy

### a) tworzenie macierzy lub wektora zerowego 

In [20]:
A = np.zeros([2, 5])
print(A)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [21]:
v = np.zeros(3)
print(v)

[0. 0. 0.]


### b) tworzenie macierzy lub wektora wypełnionych jedynkami

In [22]:
A = np.ones([3, 5])
print(A)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [23]:
v = np.ones(4)
print(v)

[1. 1. 1. 1.]


### c) dla innej wybranej liczby

In [24]:
A = np.full([2, 3], 11)
print(A)

[[11 11 11]
 [11 11 11]]


In [25]:
v = np.full(3, 3.1)
print(v)

[3.1 3.1 3.1]


### d) tworzenie macierzy lub wektora z losowymi liczbami z zakresu [0, 1]

In [26]:
A = np.random.sample([4, 2])
print(A)

[[0.53055356 0.96199936]
 [0.29845058 0.15875713]
 [0.53372439 0.12715172]
 [0.4053255  0.41256908]]


In [27]:
v = np.random.sample(3)
print(v)

[0.14371497 0.37435565 0.15347719]


### e) tworzenie wektora wartości [a, b) co n

In [28]:
x = np.arange(-5, 12, 1)
print(x)

[-5 -4 -3 -2 -1  0  1  2  3  4  5  6  7  8  9 10 11]


# Funkcje matematyczne w numpy 

In [29]:
a = 5
print(f'e^5: {np.exp(5)}')

e^5: 148.4131591025766


In [30]:
# funkcji możemy używać na wektorach i macierzach!
A = np.array([[0, np.pi], [np.pi / 2, np.pi * 2]])
print(A)
print('\n=================================\n')
print('Użycie funkcji sinus na każdym wyrazie macierzy A: ')
print(np.sin(A))
# UWAGA, wyrazy są zbliżone do rzeczywistych wartości, ale nie idealne!
# takie przybliżenie jednak w zupełności nam wystarczą

[[0.         3.14159265]
 [1.57079633 6.28318531]]


Użycie funkcji sinus na każdym wyrazie macierzy A: 
[[ 0.0000000e+00  1.2246468e-16]
 [ 1.0000000e+00 -2.4492936e-16]]


# Tworzenie własnych funkcji 

In [31]:
def funkcyjka(x):
    return np.log(x) + x

In [32]:
x = [1, 2, 3]
print(f'Użycie naszej funkcji na tablicy x: {funkcyjka(x)}')

Użycie naszej funkcji na tablicy x: [1.         2.69314718 4.09861229]


# Obliczanie średniej, wariancji oraz odchylenia standardowego dla danych

### a) dla wektorów

In [33]:
x = np.array([1, 2, 3, 4])
print(f'Średnia: {np.mean(x)}')
print(f'Wariancja: {np.var(x)}')
print(f'Odchylenie standardowe: {np.std(x)}')

Średnia: 2.5
Wariancja: 1.25
Odchylenie standardowe: 1.118033988749895


### b) dla macierzy 

In [34]:
A = np.array([[1, 2], [3, 4]])
# tutaj mamy kilka opcji:
print('Macierz A:')
print(A)
# a) dla wszystkich wyrazów
print(f'Średnia dla wszystkich wyrazów: {np.mean(A)}')
# b) dla kolumn
print(f'Średnia dla kolumn: {np.mean(A, axis=0)}')
# c) dla wierszy
print(f'Średnia dla wierszy: {np.mean(A, axis=1)}')
# wynikiem tego jest WEKTOR, numpy rozróżnia wektory i macierze!
# analogicznie możemy postępować dla innych funkcji statystycznych

Macierz A:
[[1 2]
 [3 4]]
Średnia dla wszystkich wyrazów: 2.5
Średnia dla kolumn: [2. 3.]
Średnia dla wierszy: [1.5 3.5]


# Pozostałe przydatne funkcje

In [35]:
# funkcja where
x = np.arange(2, 10, 1)
# wybieramy tylko liczby parzyste
y = np.where(x % 2 == 0, 1, 0)
print(x)
print(y)

[2 3 4 5 6 7 8 9]
[1 0 1 0 1 0 1 0]


In [36]:
# funkcja unique
x = [0, 11, 0, 4, 10, 11, 4]
print(f'Unikalne wartości dla listy x: {np.unique(x)}')

Unikalne wartości dla listy x: [ 0  4 10 11]


In [37]:
# więcej znajdziecie w dokumentacji biblioteki (albo wpisując to, co chcecie zrobić w googla)